BSR-fix-ci-cd

diff --git a/.github/workflows/reusable_deploy_mkdocs.yml b/.github/workflows/reusable_deploy_mkdocs.yml
--- a/.github/workflows/reusable_deploy_mkdocs.yml
+++ b/.github/workflows/reusable_deploy_mkdocs.yml
@@ -48,7 +48,15 @@ jobs:
 
       - name: Install Default Python requirements
         run: uv sync
-
+      - name: "Print DBT_FOLDER"
+        working-directory: "."
+        env:
+          DBT_TARGET_PATH: ${{ env.DBT_FOLDER }}/target/
+          DBT_PROFILES_DIR: ${{ env.DBT_FOLDER }}/
+          ENV_SHORT_NAME: ${{ inputs.ENV_SHORT_NAME }}
+          APPLICATIVE_EXTERNAL_CONNECTION_ID: ${{ inputs.APPLICATIVE_EXTERNAL_CONNECTION_ID }}
+          IS_CI: "true"
+        run: echo "DBT_FOLDER=$DBT_FOLDER"
       - name: "compile dbt project"
         working-directory: "."
         env:
@@ -58,7 +66,17 @@ jobs:
           APPLICATIVE_EXTERNAL_CONNECTION_ID: ${{ inputs.APPLICATIVE_EXTERNAL_CONNECTION_ID }}
           IS_CI: "true"
         run: uv run dbt deps --project-dir $DBT_FOLDER && uv run dbt compile --project-dir $DBT_FOLDER --target $ENV_SHORT_NAME --vars "{'ENV_SHORT_NAME':'$ENV_SHORT_NAME'}"
-
+      - name: "List DBT target directory"
+        working-directory: "."
+        env:
+          DBT_TARGET_PATH: ${{ env.DBT_FOLDER }}/target/
+          DBT_PROFILES_DIR: ${{ env.DBT_FOLDER }}/
+          ENV_SHORT_NAME: ${{ inputs.ENV_SHORT_NAME }}
+          APPLICATIVE_EXTERNAL_CONNECTION_ID: ${{ inputs.APPLICATIVE_EXTERNAL_CONNECTION_ID }}
+          IS_CI: "true"
+        run: |
+          echo "Listing DBT target directory:"
+          ls -R $DBT_TARGET_PATH || echo "Target path not found!"
       - name: Build MkDocs site
         working-directory: "."
         env:
